//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public string PNR { get; set; }
        public int Seat_number { get; set; }
        public string Passenger_name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public int Train_ID { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }

        public string ReservationStatus { get; set; }

        public DateTime JourneyDate { get; set; }
        public virtual Train Train { get; set; }
    }
}
