//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Train_ID { get; set; }
        public string Available_Date { get; set; }
        public string EmailID { get; set; }
        public string PNR { get; set; }
        public string Reservation_Date { get; set; }
        public string Reservation_Status { get; set; }
    
        public virtual Train_status1 Train_status1 { get; set; }
    }
}
