//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train_class
    {
        public int Train_ID { get; set; }
        public int Fare_Class1 { get; set; }
        public int Seat_Class1 { get; set; }
        public int Fare_Class2 { get; set; }
        public int Seat_Class2 { get; set; }
        public int Fare_Class3 { get; set; }
        public int Seat_Class3 { get; set; }
    }
}
