//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public Train()
        {
            this.Passengers = new HashSet<Passenger>();
            this.Passenger_ticket = new HashSet<Passenger_ticket>();
            this.Routes = new HashSet<Route>();
            this.Train_status1 = new HashSet<Train_status1>();
        }
    
        public int Train_ID { get; set; }
        public string Train_name { get; set; }
        public string Train_type { get; set; }
        public string Source_stn { get; set; }
        public string Destination_stn { get; set; }
        public Nullable<int> Source_ID { get; set; }
        public Nullable<int> Destination_ID { get; set; }
        public int AvailableSeat { get; set; }

        public virtual ICollection<Passenger> Passengers { get; set; }
        public virtual ICollection<Passenger_ticket> Passenger_ticket { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual ICollection<Train_status1> Train_status1 { get; set; }

        public int Fare_Class1 { get; set; }
        public int Seat_Class1 { get; set; }
        public int Fare_Class2 { get; set; }
        public int Seat_Class2 { get; set; }
        public int Fare_Class3 { get; set; }
        public int Seat_Class3 { get; set; }

        public string ArrivalTime { get; set; }
        public string Departure_time { get; set; }

        
    }
}
