//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailwaySystemEntities : DbContext
    {
        public RailwaySystemEntities()
            : base("name=RailwaySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin_table> Admin_table { get; set; }
        public DbSet<Days_Available> Days_Available { get; set; }
        public DbSet<Passenger> Passengers { get; set; }
        public DbSet<Passenger_ticket> Passenger_ticket { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
        public DbSet<Route> Routes { get; set; }
        public DbSet<Route_HAS_Station> Route_HAS_Station { get; set; }
        public DbSet<RS_Registration> RS_Registration { get; set; }
        public DbSet<Station> Stations { get; set; }
        public DbSet<Train> Trains { get; set; }
        public DbSet<Train_class> Train_class { get; set; }
        public DbSet<Train_status1> Train_status1 { get; set; }
        public DbSet<User_table> User_table { get; set; }
    }
}
