//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int Train_ID { get; set; }
        public int Stop_number { get; set; }
        public string Station_ID { get; set; }
        public string Arrival_time { get; set; }
        public string Departure_time { get; set; }
        public int Source_distance { get; set; }

        public string Station_Name { get; set; }
        
        public virtual Train Train { get; set; }
    }
}
